README.md

Build is currently unknown, but will have a status after the next commit to master.

Add build badge for Travis to README

---

lang/nn.js

Adds a Norwegian Nynorsk translation. There are already translations for jQuery UI datepicker and moment.js.

Added Norwegian Nynorsk translation

---

src/common/Grid.events.js

use _this to access Grid.largeUnit property

use _this to access Grid.largeUnit property

---

src/common/Grid.events.js
src/common/Grid.js

add support for eventLongPressDelay and selectLongPressDelay properties

---

src/common/DayGrid.limit.js
tasks/locale.js
tests/automated/eventLimit-popoverDestroy.js

https://github.com/fullcalendar/fullcalendar/issues/3416

fixes #3416, eventDestroy not called when removing the popover

---

locale/bn.js

I am not sure about the `allDayHtml`. So left it as it is. If you can explain, then I will correct it too.

Added Bengali support

---

locale/zh-tw.js

update some translate

---

demos/theme-bootstrap.html
src.json
src/Calendar.js
src/Calendar.render.js
src/Toolbar.js
src/agenda/AgendaView.js
src/basic/BasicView.js
src/common/DayGrid.js
src/common/DayGrid.limit.js
src/common/DayTableMixin.js
src/common/Grid.js
src/common/Theme.js
src/common/TimeGrid.js
src/common/View.js
src/common/common.css
src/defaults.js
src/list/ListView.js

I've hacked together a simple implementation of #2334. It has some visual issues, but it's usable overall.
If this is still on the roadmap I could spend some time improving the implementation.

Bootstrap themes

---

locale/sr-cyrl.js
locale/sr.js

Translation of interface in serbian cyrilic.

Serbian (cyrlic) translation [skip ci]

---

src/common/TimeGrid.js

fix isLabeled flag with minTime / labelInterval is not Integer
issue: https://github.com/fullcalendar/fullcalendar/issues/2786

slotDuration invisible when minTime starts out of alignment

---

locale/sq.js

Under ISO standards Albanian two letter code is 'sq'

Creating sq.js for the Albanian language

---

src/View.js
src/agenda/TimeGrid.js
tests/event-render/minSegmentHeight.js

Issue: https://github.com/fullcalendar/fullcalendar/issues/961
Fiddle illustrating the problem: http://jsfiddle.net/jc1zx2q6/5/
Fiddle illustrating the solution: https://plnkr.co/edit/t5eAi1raDw4ZexwCrWy6?p=preview

Add agendaEventMinHeight option to prevent short events overlapping

---

src/agenda/AgendaView.js
src/basic/BasicView.js
src/defaults.js
tests/legacy/columnFormat.js

Solves #3438.
See a demo here: https://plnkr.co/edit/W8nw1DKVenJV72QMrhn8?p=preview

add columnHead option to show/hide column heading (#3438)

---

selection/unselect_callback.txt

fix #3341 (unselect callback return order)

---

tests/legacy/DayGrid-events.js
tests/legacy/addEventSource.js
tests/legacy/allDaySlot.js
tests/legacy/allDayText.js
tests/legacy/businessHours.js
tests/legacy/columnFormat.js
tests/legacy/constraint.js
tests/legacy/constructor.js
tests/legacy/current-date.js
tests/legacy/custom-view-class.js
tests/legacy/custom-view-duration.js
tests/legacy/external-dnd-advanced.js
tests/lib/dnd-resize-utils.js

updated tests/legacy/{addEventSource,allDaySlot,AllDayText,BusinessHours,columnFormat,DayGrid-events}.js

updated legacy tests 

---

tests/legacy/defaultAllDayEventDuration.js
tests/legacy/defaultTimedEventDuration.js
tests/legacy/destroy.js
tests/legacy/displayEventEnd.js
tests/legacy/event-feed-param.js
tests/legacy/event-obj.js
tests/legacy/eventAllow.js
tests/legacy/eventLimit-popover.js
tests/legacy/eventLimit-popoverDestroy.js
tests/legacy/eventLimit.js
tests/legacy/eventLimitClick.js
tests/legacy/eventLimitText.js
tests/legacy/eventRender.js
tests/legacy/eventRenderWait.js
tests/legacy/events-function.js
tests/legacy/events-json-feed.js
tests/legacy/formatRange.js
tests/legacy/moment-construct.js
tests/legacy/moment-misc.js
tests/legacy/now.js
tests/legacy/selectAllow.js
tests/legacy/selectHelper.js
tests/legacy/themeButtonIcons.js
tests/lib/time-grid.js

Starting new batch of updates to legacy tests
https://github.com/fullcalendar/fullcalendar/wiki/Initiatives#how-to-rewrite-legacy-initialization-calls-in-tests

Converting Constructors in Legacy Tests

---

locale/ka.js

This PR adds Georgian (ka) translations

Add Georgian (ka) locale

---

src/list/ListView.ts

Fix for issue described in #3346.

Fix auto height in ListView.

---

locale/nl.js

https://fullcalendar.freshdesk.com/a/tickets/165

Add translation of "year" in dutch

---

tests/automated/legacy/forceEventDuration.js
tests/automated/legacy/header-rendering.js
tests/automated/legacy/locale.js
tests/automated/legacy/maxTime.js
tests/automated/legacy/monthNames.js
tests/automated/legacy/monthNamesShort.js
tests/automated/legacy/navLinks.js
tests/automated/legacy/nextDayThreshold.js
tests/automated/legacy/nowIndicator.js
tests/automated/legacy/refetchEvents.js
tests/automated/legacy/removeEvents.js
tests/automated/legacy/scroll-state.js
tests/automated/legacy/slotDuration.js
tests/automated/legacy/updateEvent.js
tests/automated/legacy/viewDestroy.js
tests/automated/legacy/weekNumberCalculation.js

Update legacy tests

---

src/types/input-types.ts

Fix type definition for eventAllow callback

---

src/core/types/input-types.ts

fix dateClick event argument typings

---

packages/core/src/locales/az.js

Is there any update on this? 🙂

Azerbaijan Language Pack Added

---

packages/core/src/locales/fr.js

Just Planning not "Mon Planning" because it can be an other way (like other user)

French translation for "list" is "my schedule" but should be just "schedule"

---

packages/core/src/locales/el.js

A small translation fix for the greek (el) locale.

minor translation fix

---

locale/pt-br.js

Added:
dayNames,
dayNamesShort,
monthNames,
monthNamesShort

Update locale pt-br

---

lang/ug-cn.js

Hi,
Thanks for the great library. Here is Uyghur translation of select2, hope you can merge it. Thanks a lot.
Best,
Alim

Added Uyghur language

---

packages/core/src/locales/de-at.ts

eg. Austrians prefer Jänner over Januar

i18n: Add Austrian locale

---

packages/core/src/locales/bn.ts

Hi, I have added the Bengali language for this awesome plugin. Please review and approve.

bengali Language Added

---

packages/core/src/locales/sm.ts

Added Samoan language translation file by following contribution steps.

Add samoan locale

---

packages/core/src/locales/lka.ts

Add Sinhala language data to locales (Sri Lanka)

Add Sinhala  (Sri Lanka) translations  (si_LK)

---

packages/core/src/locales/nb.ts

New options for locale. Ref https://github.com/fullcalendar/fullcalendar/blob/master/CHANGELOG.md#v5100-2021-10-13

New locale options for Norwegian

---

packages/core/src/locales/fr.ts

Add weekTextLong to the French translation

---

packages/core/src/locales/gl.ts

This PR adds some additional strings that are in the Spanish language but not in Galician.

Update Galician Locale

---

packages/core/src/locales/pt-br.ts

Some buttons and texts were not translated into Brazilian Portuguese. Please merge into the project.

Update pt-br Locale
