.travis.yml, package.json, tests/automated/refetchEvents.js, tests/automated/removeEventSource.js, tests/automated/removeEventSources.js
This should speed up subsequent runs by caching `node_modules` and `lib`.
Additionally, this adds linting to Travis, and fixes existing lint problems in the tests.
----
Example run: https://travis-ci.org/avindra/fullcalendar/builds/143421961
=> Travis: add style checks to CI and speed up runs

CHANGELOG.md, src/Calendar.js, tests/automated/height-and-contentHeight.js, tests/fullheight.html
This is a fork of #3040. Instead of adding a new `getContainerHeight` option, this simply allows height and contentHeight to accept a function.
See a preview here: http://plnkr.co/edit/O0iBHMcFa0faPE8XyPb3?p=preview where `height` is a function that returns the height of the calendar's parent (which is an absolutely positioned DIV with `{top: 200px, right: 0, bottom: 0, left: 0;}`).
=> allow height/contentHeight to accept a function for dynamic value

src/Calendar.js
**From commit message**
ISO 8601 defines Monday as the first day of the week. This means that when setting `weekNumberCalculation: 'ISO'`, week numbers will change on Monday, regardless of the locale used.
However, some locales define another day as first day of the week (`dow`). As said, that will not influence ISO week number calculation, but it _does_ determine the day on which each week row starts in the calendar display (which day is in the left-most day column).
This can lead to a single row in the calendar having a week number change somewhere halfway down the week. For example, a calendar row displaying Sunday through Saturday according to US English locale, with the week number changing on Monday according to ISO 8601 week number calculation. Then when displaying week numbers …
=> Default firstDay to 1 for ISO week calculation

src/common/print.css
Fullcalendar's print stylesheet was overriding table styles globally. This commit scopes the rules.
Updated #3303 for 3.0.0.
I have compared month/agendaDay view printouts before and after the change and they match.
=> Add .fc scope to table print styles

text/buttonText.txt
Update the buttonText documentation to include list for the List View button.
=> Include list option in documentation

src/EventManager.js
`batchRenderEvent`/`batchUpdateEvent` will be a substitute for `renderEvent`/`updateEvent` when you have more then one event to render/update.
Input: `arrayOfEvents, stick`
Output: `arrayOfRenderedEvents`
`renderEvent` will call `reportEvents` every call, so calling it in a loop is very expensive. I have created `batchRenderEvent` to overcome this.
Speed comparison: http://jsbin.com/gugowemivu/edit?js,console,output
I didn't make an automated test because `renderEvent` also doesn't have one.
Possible fix for: #2938 
Helps for: #2524
=> Add batch-render methods: renderEvents and updateEvents

src/date-formatting.js, tests/automated/formatRange.js
I humbly request that this change be merged into master. It fixes a problem I'm encountering where week numbers are duplicated in the title, when the start and end weeks for a view are equal.
If not, can you guys elaborate on why it should not be merged? I can see the bug ( https://github.com/fullcalendar/fullcalendar/issues/2636 ) has been open for quite a while now, and it's marked as "todo" in the code.
=> add week to similarUnitMap (also fixes issue 2371)

src/common/Grid.events.js, tests/automated/background-events.js
I found a bug with inverse-background events when 2 events have the same id and one range is included in the other.
For instance, with a range = 2am → 7am and a range = 3am → 5am, you would expect the result of `invertRanges()` to be 
``` js
[
{
"start": "2017-03-07",
"end": "2017-03-07T02:00:00"
},
{
"start": "2017-03-07T07:00:00",
"end": "2017-03-08"
}
]
```
but it is 
``` js
[
{
"start": "2017-03-07",
"end": "2017-03-07T02:00:00"
},
{
"start": "2017-03-07T05:00:00",
"end": "2017-03-08"
}
]
```
Here is a codepen demonstrating this: http://codepen.io/floriancargoet/pen/gmQePw
When you check the execution of the `invertRanges` function, you can see that after sorting the ranges we have `ranges = [2am → 7am , 3am → 5am]`. Then we push (viewStart → 2am) in the `inverseRanges` array, set …
=> Bug with nested inverse-background events (test & fix included)

composer.json
Hello!
Related to #2999 
This piece is necessary to have fullcalendar package on packagist.org. Unfortunately, there are some steps I can't do for you, like create an account in packagist.org, submit your package and wire packagist to github webhooks. But it takes less than 10 minutes.
The `name` info on composer.json should be equals to your account name and package name on packagist.org.
It would be awesome to have your library on packagist.
Thank you!!
=> Add composer.js to let PHP developers to keep track of fullcalendar on packagist.org.

src/moment-ext.js, tests/automated/moment-ambig.js
Some locales do a post-processing step when formatting. For example Arabic does that:
```javascript
$.fullCalendar.moment.parseZone('2014-06-08T10:00:00').locale('ar').format()
// result: "٢٠١٤-٠٦-٠٨T١٠:٠٠:٠٠"
```
There is a bug in `moment-ext.js` which causes calls to `toISOString` use this post-processing:
```javascript
$.fullCalendar.moment.parseZone('2014-06-08T10:00:00').locale('ar').toISOString()
// result: "٢٠١٤-٠٦-٠٨T١٠:٠٠:٠٠"
// expected: "2014-06-08T10:00:00"
```
This PR introduces a test for that and attempts to fix the issue in a pretty ugly way.
=> Fix toISOString for locales with non-trivial postformatting

src/theme/BootstrapTheme.js
I suggest that a more neutral color is used for today's cell highlighting.
=> Tweak the class for 'today' in the bootstrap theme

src/models/event-source/FuncEventSource.js
The current code sets the `this` context when invoking the user-defined event source function. However it uses `this.calendar`, which is undefined in the `Promise` callback. It should be using `_this` to access the correct calendar object.
The default implementation is a fairly innocuous bug and won't cause any issues unless the caller tries to use `this` in their event source function. However, if you're in `use strict` mode (i.e. you've included `fullcalendar` as part of a build-chain) the browser will throw errors and stop execution.
https://jsbin.com/sepeparuse/edit?html,js,console,output
=> Set 'this' context properly in FuncEventSource

src/Toolbar.ts
Very initial work on addressing issues brought forward in #2536. Began by trying to address ARIA labeling of previous/next buttons which only use icons.
**Open Questions**
1. Any advice on the approach or specific implementation details would be appreciated.
2. Are tests desired to check for the attribute? How to test a11y?
2. It doesn't seem there is currently appropriate text for these buttons, which for English would be "Previous" and "Next" and would be needed in all other locales as well, so what is the appropriate way to acquire this text? Can we start with a few common locales?
3. What else is needed to make this addition viable?
Any feedback would be appreciated, thanks!
=> Add aria-label to toolbar icon buttons

src/exports.ts, src/types/jquery-hooks.ts
Exposed `OptionsInput` for the ability to type externally created fullcalendar options.
Fixed two optional parameters in `jquery-hooks` based on:
- [https://fullcalendar.io/docs/event_data/removeEvents/](https://fullcalendar.io/docs/event_data/removeEvents/)
- [https://fullcalendar.io/docs/views/changeView/](https://fullcalendar.io/docs/views/changeView/)
=> Expose missing OptionsInput type and fix some jquery hooks types

locale/sv.js
The previous abbreviation "Ve" is not correct and does not follow any standards. I've changed the abbreviation to `v. ` including a trailing whitespace which becomes `v. 9`. This is the correct way to shorten "week" in swedish.
**Source:**
[https://sv.wiktionary.org/wiki/v.](https://sv.wiktionary.org/wiki/v.)
`2. förkortning för vecka` which translates to `2. abbreviation for week`.
=> Corrected the swedish week header.

bower.json
Motivation: Handling of Chinese dates are broken in Nextcloud (https://github.com/nextcloud/calendar/issues/534). It turns out that locale handling was broken in older moment.js versions. This is fixed in https://github.com/moment/moment/pull/3952 and included in moment.js 2.20.0.
=> bower: bump moment to 2.20.1, which includes Chinese fixes

locale/de.js
This commit fixed the issue #4370:
With "lang" set to "de", the heading of agendaweek is missing a dot after the month number
Expected output for 2018-11-06:
"Di. 06.11."
Actual:
"Di. 06.11"
See this MCVE: http://jsfiddle.net/41sc3ed5/3
=> Issue #4370: Wrong date formatting in agendaWeek with German locale

src/types/input-types.ts
Typescript definitions for `selectAllow` (https://fullcalendar.io/docs/selectAllow) was missing.
=> Added typescript definition for selectAllow

locale/de-at.js, locale/de-ch.js, locale/de.js
See https://github.com/fullcalendar/fullcalendar/issues/4193.
But there are still lots of language files without the year-buttonText translation.
=> Added buttonText year translation for the german files.

src/View.ts
If you wish to see what this fixes, please see the JSFiddle in the below issue.
Adresses https://github.com/fullcalendar/fullcalendar-scheduler/issues/416
=> Fix bug preventing resizing of event from the left / delta undefined error

plugins/gcal/GcalEventSource.ts
Implements feature request #4122 
Extended properties allow you to set some meta data on google calendar events. They are not visible but can be set through the Google API. This is often used for meta data, like a tag or category for your event. 
It would be super nice to attach a class depending on an extended property, or influence how an event is rendered. However, the gcal plugin doesn't pass the properties along to the fullcalendar event.
Just pass along the shared extende properties to the fullcalendar event. The fix is small yet does the trick.
=> GCal: pass extendedProperties along

src/core/types/input-types.ts
As instructed on a fullcalendar/scheduler issue (https://github.com/fullcalendar/fullcalendar-scheduler/issues/508) I'm using `viewSkeletonRender` function to replace the Resource Header element after the initial render.
This breaks the TypeScript build, because `viewSkeletonRender` is not on the `OptionsInput` interface.
This PR just adds `viewSkeletonRender` to the `OptionsInputBase` interface.
=> adding viewSkeletonRender function to OptionsInputBase interface

CONTRIBUTING.md
The following link to the Google Style Guide is not working anymore:
http://google-styleguide.googlecode.com/svn/trunk/javascriptguide.xml
The new link is:
https://google.github.io/styleguide/jsguide.html
=> Fix link to Google Style Guide

package.json
We are having the same problem as [ColorlibHQ Issue #678](https://github.com/ColorlibHQ/gentelella/issues/687).
```npm run sass``` is failing because we are still using the ```--sourcemap``` option.
This PR is a simple update to using ```--no-sourcemap``` instead of ```--sourcemap=none```
Please see [sass-lang's documentation](https://sass-lang.com/documentation/cli/dart-sass#no-source-map) for this option if you have any questions.
=> Updated sass script

src/core/Calendar.ts, src/core/component/DateComponent.ts, src/core/component/event-rendering.ts, src/core/interactions/EventClicking.ts, src/core/interactions/EventHovering.ts, src/core/interactions/event-dragging.ts, src/core/types/input-types.ts, src/interaction/interactions-external/ExternalElementDragging.ts, src/interaction/interactions/EventDragging.ts, src/interaction/interactions/EventResizing.ts
This PR prevents `OptionsInput` event-handler typings from getting out-of-sync with code that triggers events.  It does this by adding type safety to event-triggering methods in FullCalendar.  If an event is triggered with the wrong parameter type or event name, a compiler error will result.  This should prevent handler-typing problems from happening in the future, as well as making it easy to find event-handler typing issues in current code.  Fixes #4656. Fixes #4654.
Because types are inferred based on the event name (e.g. `'drop'` or `'eventMouseLeave'`), no code changes are needed for existing or future event-triggering code, except to fix compiler errors caused by passing the wrong types or by mistakes in type declarations. 
Speaking of "_mistakes in type declarations_", this PR also …
=> Type-safe event handlers (and fix OptionsInput event handler typings)

.travis.yml
All builds are failing because of a problem with Travis's support of Node 12 yet. https://discourse.elm-lang.org/t/travis-build-failing-and-other-occassions/3546
This PR switches the Travis build config from using the latest Node to instead stick to Node 11 so that builds will work again.
When Travis builds on Node 12 are working, this change should be reverted.
Fixes #4649
=> Go back to Node 11 until Travis has Node 12 support

locales/da.js
The correct spelling is two words: https://ordnet.dk/ddo/ordbog?query=i%20dag
=> Fix typo in Danish locale file

src/core/datelib/env.ts, tests/automated/legacy/firstDay.js
According to the [docs](https://fullcalendar.io/docs/firstDay) when weekNumberCalculation is set to 'ISO' it defaults to firstDay setting to Monday. But with the current code the firstDay setting is ignored when weekNumberCalculation is ISO.
- Load a calendar
- Set the firstDay setting to 3
- Set the weekNumberCalculation setting to 'ISO'
The result is that it shows Monday as first day in week.
Pen to test it is here https://codepen.io/anon/pen/PrNdwo
=> Respected FirstDay setting even with week calc ISO

packages/google-calendar/src/main.ts
This makes the GOOGLE_API_BASE configurable in @fullcalendar/google-calendar and fixes https://github.com/fullcalendar/fullcalendar/issues/4953
Im not very experienced in typescript and monorepos, but i just gave it a shot.
Any advice is welcome.
=> made GOOGLE_API_BASE configurable, fixes #4953

src/Toolbar.ts, src/agenda/AgendaView.ts, src/agenda/TimeGrid.ts, src/agenda/TimeGridEventRenderer.ts, src/basic/DayGrid.ts, src/basic/DayGridEventRenderer.ts, src/basic/DayGridFillRenderer.ts, src/basic/DayGridHelperRenderer.ts, src/list/ListView.ts, src/util.ts
In 3.5, jQuery changed the jQuery.htmlPrefilter to no more
XHTML-compliant. So tags must be closed for HTML.
=> Add support for jQuery 3.5

packages/daygrid/src/TableListItemEvent.tsx
Due to the way it's implemented, the colored dot in the daygrid view depends on `borderColor` for its color. However, in the code, `backgroundColor` was set, resulting in the dot not being able to change color.
This PR changes `backgroundColor` to `borderColor`, enabling changing the color of the dot as was originally intended. There are not side effects.
=> fix: wrong daygrid TableListItemEvent dot color

packages/__tests__/src/datelib/rrule.js, packages/rrule/src/main.ts
This fixes an issue with the rrule plugin parsing rrule strings without taking the current timezone into account.
This fix is suggested by @paco3346 in issue #4955 and I take no credit for it. It seems to fix a problem that I really want to see fixed, so I took the liberty of creating this pull request. The first one I've ever created. :)
=> Make sure @fullcalendar/rrule parses rrules given as strings the same as rrules given as objects

packages/__tests__/src/legacy/dateClick.js, packages/__tests__/src/legacy/event-dnd.js, packages/__tests__/src/legacy/select-callback.js
There is a small typo in packages/__tests__/src/legacy/dateClick.js, packages/__tests__/src/legacy/event-dnd.js, packages/__tests__/src/legacy/select-callback.js.
Should read `discrimination` rather than `descrimination`.
=> docs: Fix simple typo, descrimination -> discrimination

packages/rrule/src/main.ts
adds exdates and exrules as options for rrule with rruleset
Implements #4439, #4549, #5642
Implementation based on #5097 != > a bit more readable and up to date with v5.
=> Add exdates and exrules as options for rrule plugin's object

package.json
While getting the dev environment setup and playing around with some of the commands, I noticed that this particular command was pointing at the wrong location. This PR fixes that.
./script/example-open.sh -> ./scripts/example-open.sh
=> package.json: fix example:open call

packages/google-calendar/src/main.ts
Addresses https://github.com/fullcalendar/fullcalendar/issues/5024
Turns out attachments are [returned on the event objects](https://developers.google.com/calendar/v3/reference/events) themselves by Google.
Adding them as properties to the rawEventDef makes them propagate to extendedProperties in the FullCalendar Event so this should be the only change necessary to allow us to have access to the same attachment info
=> add google attachments to event extendedProps

packages/rrule/src/main.ts
Include \n in UNTIL regex exclusion. This fixes input strings such as:
```
DTSTART;TZID=America/New_York:20210112T080000
RRULE:FREQ=MONTHLY;UNTIL=20210110T070000
RDATE;TZID=America/New_York:20210112T080000
```
Without this fix, parsing this input string results in a null exception.
=> fix UNTIL at the end of rrule

packages/icalendar/src/main.ts
The starting time was defined in the iCalEvent.iterator call wrongly as UTC midnight, whereas it should be the iCalEvent.startDate (the default when no arguments are given).
For an example of this going wrong, see this calendar with some test recurring events: https://ical-cors-proxy.herokuapp.com/?https://use01.thegood.cloud/remote.php/dav/public-calendars/BHNK5Arjn4S7GMGX/?export
On the current master branch, the recurring event dates are all at UTC midnight. With this branch, they will correctly be the time as set in the ICAL.
=> Fix ICAL recurring event start and end times

packages/icalendar/src/main.ts
This pull request will load the event organizer, location and description from ICAL calendars when using them as an event source. They are inserted as attributes of event.extendedProps.
This should make some common ICAL usecases possible, and solves #6097
=> Feature: Add location, organizer and description from ICAL events

packages/daygrid/src/Popover.tsx
fixes #6205
**Description**
Popover closing each time by click inside Popover. Problem actual when we using Fullcalendar inside the Shadow DOM. Click listener has an incorrect target because target equals shadow dom root element. Example: https://codesandbox.io/s/recursing-pascal-cg0md?file=/src/full-calendar-component.js.
Current PR fixes the problem via `composedPath()` https://developer.mozilla.org/en-US/docs/Web/API/Event/composedPath
=> fix Popover closing inside Shadow DOM

packages/core/src/locales/hu.ts
The previous Hungarian translation "napló" is foreign in this context, it literally means "journal". Agenda in calendar context is better translated as "napirend" or "lista". I suggest "lista" (lit. list) which is a clear descrption of the list view. (I'm a native speaker.)
See human-curated Hungarian-English dictionary: https://szotar.sztaki.hu/search?fromlang=eng&tolang=hun&searchWord=agenda&langcode=hu&u=0&langprefix=&searchMode=WORD_PREFIX&viewMode=full&ignoreAccents=0
=> Fix Hungarian term for "agenda"

packages/core/src/locales/ku
This file contains a Kurdish (Central Kurdish) translation. However, monthNames and dayNames are not defined here. Therefore, they are not added. This problem was mentioned in issue "Add Welsh locale (cy-GB) #5572" as well but still don't know how to fix it.
=> Add Kurdish (Central Kurdish)

packages/rrule/src/event-refiners.ts
The `freq` property in `RRuleInputObject` was incorrectly typed as the `until` property of `RRuleOptions`, not `freq`.
=> Fix freq property type

packages/core/src/locales/fr-ca.ts, packages/core/src/locales/fr-ch.ts, packages/core/src/locales/fr.ts
Updated French (and -ca and -ch) locale for a typo on the word "évènement".
While both are correct, "évènement" would be the new standard (since 1990).
Here's a article (in french) explaining all of that: https://www.lalanguefrancaise.com/orthographe/evenement-ou-evenement-orthographe
=> replace "évènement" in french locales

packages/core/src/util/misc.ts
#7441 
fixes this issue, when pressing long on iPad to select date or time in calendar, that all text gets marked.
=> fix(#7441) - fixed selection on pressing long

packages/core/src/locales/ca.ts
Year translated into Catalan is "Any". 
"Curs" is course in english.
=> Fix translation CA

packages/core/src/locales/nl.ts
`List` in Dutch isn't `Agenda` but `Lijst`
`Agenda` means `Calendar`/`Agenda` when translated into English from Dutch
=> fix translation 'list' in NL
